#pragma once

enum DriveTrain_State{DRIVE, OFF}; 
enum System_State{UNFOLD, UNFOLD_ARM_ZERO, TRAY_ZERO, BASE, ARM1, ARM2, ARM3, ARM_ZERO, POSITION_CUBES, TRAY_VERTICAL};
enum Button_Enums{BUTTONA, BUTTONB, BUTTONY, BUTTONX, BUTTONL1, BUTTONL2, BUTTONR1, BUTTONR2, BUTTONUP, BUTTONRIGHT, BUTTONLEFT, BUTTONDOWN};
enum Axis_Enums{AXIS1, AXIS2, AXIS3, AXIS4};