#pragma once

enum DriveTrain_State{DRIVE, DRIVE_BACK_STATE, OFF}; 
enum System_State{UNFOLD, UNFOLD_ARM_ZERO, TRAY_ZERO, BASE, ARM1, ARM2, ARM_ZERO, POSITION_CUBES, TRAY_VERTICAL};
enum Auto_State{FORWARD, MORE_FORWARD, TURN_ONE, LEFT, RIGHT, TURN_TWO, BACK, CLEAR, TURN_THREE, TO_STACK, POSITION_CUBES_AUTO, TRAY_VERTICAL_AUTO, OUTTAKE, STOP_AUTO};
enum Button_Enums{BUTTONA, BUTTONB, BUTTONY, BUTTONX, BUTTONL1, BUTTONL2, BUTTONR1, BUTTONR2, BUTTONUP, BUTTONRIGHT, BUTTONLEFT, BUTTONDOWN};
enum Axis_Enums{AXIS1, AXIS2, AXIS3, AXIS4};